sudo: required
services:
  - docker

before_install:
  - docker build -t rivabu/docker-angular -f Dockerfile.dev .

script:
  - docker run -e CI=true rivabu/docker-angular ng test --watch=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-angular"
  env: "DockerAngular-env"
  bucket-name: "elasticbeanstalk-us-east-2-007175125099"
  bucket-path: "docker-angular"
  on:
    branch: master

  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
